name: macOS Runner Tests
on: [push]
jobs:
  Command-Test:
    strategy:
      matrix:
        version: [macos-12, macos-11, macos-10.15]
    runs-on: ${{ matrix.version }}
    steps:
      - run: python -V
      - run: python3 -V
